# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compile and Release

on:
  push:
    tags:
      - "test"

jobs:  
  build:
    name: Compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          echo Install Poetry and use it to create the virtual environment
          echo 
          pip3 install poetry
          poetry env use python
          poetry show --tree
          poetry install

      - name: Compile obs_pS on MacOS
        #if: contains(matrix.os, macos-latest)
        run: |
          echo Compile program with pyinstaller4.2
          echo
          #poetry run pip3 install pyinstaller
          poetry add pyinstaller
          echo Run pyinstaller
          poetry run pyinstaller scripts/obs_pS.py --noconsole
          zip -r obs2.zip dist/
      
      #- name: Zip the dist folder
      #  uses: papeloto/action-zip@v1
      #  with:
      #    files: dist
      #    dest: obs.zip
        
      #- name: Zip the dist folder
      #  uses: thedoctor0/zip-release@master
      #  with:
      #    type: 'zip'
      #    filename: 'obs2.zip'
      #    path: dist
      
      - name: Check directory
        run: |
          echo Directory
          ls
          echo
          echo dist
          ls dist
          echo
          echo Original folder size
          du -sh dist
          echo Zipped size 1
          #du -sh obs.zip
          echo Zipped size 2
          du -sh obs2.zip
          echo Zipped size 3
          #du -sh dist/obs_pS
          file dist/obs_pS
          
      
      - name: Create release and upload assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "obs2.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
    
