# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compile and Release

on:
  push

jobs:  
  build:
    name: Compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          echo Install Poetry and use it to create the virtual environment
          echo 
          pip3 install poetry
          poetry install

      - name: Compile obs_pS on MacOS
        #if: contains(matrix.os, macos-latest)
        run: |
          echo Compile program with pyinstaller4.2
          echo
          poetry run pip3 install pyinstaller==4.2
          poetry run pyinstaller scripts/obs_pS.py --onefile
          
      - name: Create release
        id : create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          
      - name: Check directory
        run: |
          echo ls ${{ github.workspace }}
          echo ls dist
          ls
      
      - name: Zip the dist folder
        uses: papeloto/action-zip@v1
        with:
          files: dist
          dest: obs.zip
      
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: obs.zip
        
    
